### ISSUE TITLE
Install on Ubuntu 20.04

### ISSUE THREAD

**Issue by rogfree741** [MiKTeX/docker-miktex-build-xenial#5]
Looks like :
Looking at [the installation directions on the site](https://miktex.org/download), you may need to change the line in your miktex.list file to this:

deb http://miktex.org/download/ubuntu focal universe

==> bionic universe  should be changed on download page of miktex,org

  sorry if redundant
        roger

**Comment by edocevoli** [comment]
Thank you, will take a look.
